version: '3.1'

services:
  'laravel':
    build:
      context: Docker/
      dockerfile: DockerfileLaravelProd
    image: laravel/php:73
    container_name: laravel
    restart: unless-stopped
    depends_on:
      - maria
      - composer
      - node
    links:
      - maria:db
      - redis:redis
    volumes:
      - ./Website/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./Website/htdocs:/var/www/html

  queue:
    image: ipunktbs/laravel-queue-worker
    container_name: queue
    restart: unless-stopped
    volumes:
      - ./Website/htdocs/mpmanager:/var/www/app
    depends_on:
      - maria
      - redis
    links:
      - redis:redis
      - maria:db
    environment:
      - LARAVEL_HORIZON=true

  'composer':
    container_name: mpmanager_composer
    build:
      context: Docker/
      dockerfile: DockerfileComposer
    restart: 'no'
    command: install
    volumes:
      - ./Website/htdocs/mpmanager:/app

  'node':
    container_name: mpmanager_node
    build:
      context: Docker/
      dockerfile: DockerfileNpm
    volumes:
      - ./Website/htdocs/mpmanager:/home/node/app
    command:  /bin/sh -c "/tmp/start.sh"

  'redis':
    image: redis:5
    restart: unless-stopped
    volumes:
      - ./redis/:/data

  'maria':
    container_name: maria
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./DB/mysql:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./Website/htdocs:/var/www/html
      - ./NginxProxy/conf.p:/etc/nginx/conf.d
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"